# ABOUTME: Configures GitHub secret scanning to ignore test data
# ABOUTME: Prevents false positives from test RSA keys and credentials

paths-ignore:
  - "**/testdata/**"
  - "**/*_test_*.pem"
  - "**/*_test_*.key"
